### PR TITLE
fix: adding feature store yamls for example and merging 0.25 index patch

### PR DESCRIPTION
**Pull request by franciscojavierarceo**
This PR patches a bug when running `feast apply` into the feature store. 

Without this indexing you'll get the following behavior:
```
feast apply
...
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS feature_repo_driver_hourly_stats_stream_ek (entity_key)' at line 1")
```
This is because the `index` in the `for index in cur.fetchall():` line returns this tuple: `('<feature_view_table>', 0, 'PRIMARY', 1, 'entity_key', 'A', 0, None, None, '', 'BTREE', '', '')` where `<feature_view_table>` is the output of the `_table_id(project, table)` function. Notice how the current code extracts the [2] / third element, which in this case is `'PRIMARY'`. The current value is the first index.

Additionally, the `_ek` suffix is unnecessary in mysql because the sqlite implementation uses that convention purely for naming the operation to index the table.

With the new change simply:
```
[mysql-index-patch]% feast apply
/Users/francisco.arceo/github/feast/sdk/python/feast/feature_store.py:566: RuntimeWarning: On demand feature view is an experimental feature. This API is stable, but the functionality does not scale well for offline retrieval
  RuntimeWarning,
No changes to registry
Deploying infrastructure for driver_hourly_stats_stream
Deploying infrastructure for driver_hourly_stats
[mysql-index-patch]% CURRENT_TIME=$(date -u +"%Y-%m-%dT%H:%M:%S")
[mysql-index-patch]% feast materialize-incremental $CURRENT_TIME

Materializing 2 feature views to 2022-12-28 16:26:15-07:00 into the mysql online store.

driver_hourly_stats from 2022-12-28 11:06:58-07:00 to 2022-12-28 16:26:15-07:00:
0it [00:00, ?it/s]
driver_hourly_stats_stream from 2022-12-28 11:06:58-07:00 to 2022-12-28 16:26:15-07:00:
0it [00:00, ?it/s]
```

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Review by hao-affirm — CHANGES_REQUESTED** [review]
I have doubt about this change. Especially when you feast apply instead of Galactus apply. Let Mary review it when I'm with computer

**Comment by hao-affirm** [comment]
Also the latest code is in 0.25affirm branch , the affirm might be stale

**Comment by franciscojavierarceo** [comment]
okay i'll try that branch too

**Comment by hao-affirm** [comment]
> okay i'll try that branch too

I think the main reason is the pysql version. The Galactus cli using the affirm compatible version which is lower than the latest version

**Comment by franciscojavierarceo** [comment]
> > okay i'll try that branch too
> 
> I think the main reason is the pysql version. The Galactus cli using the affirm compatible version which is lower than the latest version

i still don't think we need the `_ek` convention though but i'll test tomorrow first.

**Comment by franciscojavierarceo** [comment]
currently ml-ofs is using pymysql==0.9.3

**Comment by franciscojavierarceo** [comment]
i added pymysql==1.0.2 in this repo so i'll downgrade

**Comment by hao-affirm** [comment]
> > > okay i'll try that branch too
> > 
> > 
> > I think the main reason is the pysql version. The Galactus cli using the affirm compatible version which is lower than the latest version
> 
> i still don't think we need the `_ek` convention though but i'll test tomorrow first.

that's sth feast original implementation so i don't think we need to change it.
the issue is the old mysql doesn't support `IF NOT EXISTS` so in `0.25-affirm` branch it's sth like this:
https://github.com/Affirm/feast/blob/e51b695d5889c839dabd01a5a1eeb2c95bb0b555/sdk/python/feast/infra/online_stores/contrib/mysql_online_store/mysql.py#L202

**Comment by franciscojavierarceo** [comment]
> that's sth feast original implementation so i don't think we need to change it.
yeah but for sqlite the convention makes sense because you're naming the execution. 

see screen shot:
Screen Shot 2022-12-29 at 8 07 52 AM

in mysql I don't think it's a named operation...the ` f"ALTER TABLE {_table_id(project, table)} ADD INDEX IF NOT EXISTS {_table_id(project, table)}_ek (entity_key);"` command is actually adding the index. 

also i did try it using pymysql==0.9.3 (the one in ML-OFS) and it still gave me the same error, see output below:
```
[affirm]% python -c "import pymysql; print(pymysql.__version__)"
0.9.3
(venv) /Users/francisco.arceo/github/feast/examples/quickstart/feature_repo 
[affirm]% feast apply
/Users/francisco.arceo/github/feast/sdk/python/feast/feature_store.py:566: RuntimeWarning: On demand feature view is an experimental feature. This API is stable, but the functionality does not scale well for offline retrieval
  RuntimeWarning,
No changes to registry
/Users/francisco.arceo/github/feast/venv/lib/python3.7/site-packages/pymysql/cursors.py:170: Warning: (1050, "Table 'feature_repo_driver_hourly_stats_stream' already exists")
  result = self._query(query)
Traceback (most recent call last):
  File "/Users/francisco.arceo/github/feast/venv/bin/feast", line 8, in <module>
    sys.exit(cli())
  File "/Users/francisco.arceo/github/feast/venv/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/francisco.arceo/github/feast/venv/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/francisco.arceo/github/feast/venv/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/francisco.arceo/github/feast/venv/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/francisco.arceo/github/feast/venv/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/francisco.arceo/github/feast/venv/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/francisco.arceo/github/feast/sdk/python/feast/cli.py", line 519, in apply_total_command
    apply_total(repo_config, repo, skip_source_validation)
  File "/Users/francisco.arceo/github/feast/sdk/python/feast/usage.py", line 283, in wrapper
    return func(*args, **kwargs)
  File "/Users/francisco.arceo/github/feast/sdk/python/feast/repo_operations.py", line 336, in apply_total
    store, project, registry, repo, skip_source_validation
  File "/Users/francisco.arceo/github/feast/sdk/python/feast/repo_operations.py", line 312, in apply_total_with_repo_instance
    store.apply(all_to_apply, objects_to_delete=all_to_delete, partial=False)
  File "/Users/francisco.arceo/github/feast/sdk/python/feast/usage.py", line 294, in wrapper
    raise exc.with_traceback(traceback)
  File "/Users/francisco.arceo/github/feast/sdk/python/feast/usage.py", line 283, in wrapper
    return func(*args, **kwargs)
  File "/Users/francisco.arceo/github/feast/sdk/python/feast/feature_store.py", line 996, in apply
    partial=partial,
  File "/Users/francisco.arceo/github/feast/sdk/python/feast/infra/passthrough_provider.py", line 127, in update_infra
    partial=partial,
  File "/Users/francisco.arceo/github/feast/sdk/python/feast/infra/online_stores/contrib/mysql_online_store/mysql.py", line 202, in update
    f"ALTER TABLE {_table_id(project, table)} ADD INDEX IF NOT EXISTS {_table_id(project, table)}_ek (entity_key);"
  File "/Users/francisco.arceo/github/feast/venv/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/Users/francisco.arceo/github/feast/venv/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/Users/francisco.arceo/github/feast/venv/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/francisco.arceo/github/feast/venv/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/Users/francisco.arceo/github/feast/venv/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/Users/francisco.arceo/github/feast/venv/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/Users/francisco.arceo/github/feast/venv/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/Users/francisco.arceo/github/feast/venv/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS feature_repo_driver_hourly_stats_stream_ek (entity_key)' at line 1")
```

**Comment by hao-affirm** [comment]
> 

No, the reason is old version mysql doesn't support `IF NOT EXISTS` which is in your error.
It can create the index because the first time it create the index the `index_exists` is False so it doesn't run that `ALTER` query.
So all you need to do is remove the `IF NOT EXISTS` statement which is already in branch `0.25-affirm`: https://github.com/Affirm/feast/blob/e51b695d5889c839dabd01a5a1eeb2c95bb0b555/sdk/python/feast/infra/online_stores/contrib/mysql_online_store/mysql.py#L202

**Comment by franciscojavierarceo** [comment]
sounds good, but the other piece should still be kept then

**Comment by franciscojavierarceo** [comment]
@hao-affirm i reverted the `ek` stuff but kept the tuple position adjustment as I reproduced the break. Fails in `affirm` branch passes in this one.

```
cd /examples/quickstart/feature_repo/
[mysql-index-patch]% git checkout affirm
Switched to branch 'affirm'
Your branch is up to date with 'origin/affirm'.
(feast-affirm-py3.7) /Users/francisco.arceo/github/feast/examples/quickstart/feature_repo 
[affirm]% feast apply
/Users/francisco.arceo/github/feast/sdk/python/feast/feature_store.py:566: RuntimeWarning: On demand feature view is an experimental feature. This API is stable, but the functionality does not scale well for offline retrieval
  RuntimeWarning,
No changes to registry
/Users/francisco.arceo/Library/Caches/pypoetry/virtualenvs/feast-affirm-0Qo9tk2n-py3.7/lib/python3.7/site-packages/pymysql/cursors.py:170: Warning: (1050, "Table 'feature_repo_driver_hourly_stats' already exists")
  result = self._query(query)
Traceback (most recent call last):
  File "/Users/francisco.arceo/Library/Caches/pypoetry/virtualenvs/feast-affirm-0Qo9tk2n-py3.7/bin/feast", line 8, in <module>
    sys.exit(cli())
  File "/Users/francisco.arceo/Library/Caches/pypoetry/virtualenvs/feast-affirm-0Qo9tk2n-py3.7/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/francisco.arceo/Library/Caches/pypoetry/virtualenvs/feast-affirm-0Qo9tk2n-py3.7/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/francisco.arceo/Library/Caches/pypoetry/virtualenvs/feast-affirm-0Qo9tk2n-py3.7/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/francisco.arceo/Library/Caches/pypoetry/virtualenvs/feast-affirm-0Qo9tk2n-py3.7/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/francisco.arceo/Library/Caches/pypoetry/virtualenvs/feast-affirm-0Qo9tk2n-py3.7/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/francisco.arceo/Library/Caches/pypoetry/virtualenvs/feast-affirm-0Qo9tk2n-py3.7/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/francisco.arceo/github/feast/sdk/python/feast/cli.py", line 519, in apply_total_command
    apply_total(repo_config, repo, skip_source_validation)
  File "/Users/francisco.arceo/github/feast/sdk/python/feast/usage.py", line 283, in wrapper
    return func(*args, **kwargs)
  File "/Users/francisco.arceo/github/feast/sdk/python/feast/repo_operations.py", line 336, in apply_total
    store, project, registry, repo, skip_source_validation
  File "/Users/francisco.arceo/github/feast/sdk/python/feast/repo_operations.py", line 312, in apply_total_with_repo_instance
    store.apply(all_to_apply, objects_to_delete=all_to_delete, partial=False)
  File "/Users/francisco.arceo/github/feast/sdk/python/feast/usage.py", line 294, in wrapper
    raise exc.with_traceback(traceback)
  File "/Users/francisco.arceo/github/feast/sdk/python/feast/usage.py", line 283, in wrapper
    return func(*args, **kwargs)
  File "/Users/francisco.arceo/github/feast/sdk/python/feast/feature_store.py", line 996, in apply
    partial=partial,
  File "/Users/francisco.arceo/github/feast/sdk/python/feast/infra/passthrough_provider.py", line 127, in update_infra
    partial=partial,
  File "/Users/francisco.arceo/github/feast/sdk/python/feast/infra/online_stores/contrib/mysql_online_store/mysql.py", line 202, in update
    f"ALTER TABLE {_table_id(project, table)} ADD INDEX IF NOT EXISTS {_table_id(project, table)}_ek (entity_key);"
  File "/Users/francisco.arceo/Library/Caches/pypoetry/virtualenvs/feast-affirm-0Qo9tk2n-py3.7/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/Users/francisco.arceo/Library/Caches/pypoetry/virtualenvs/feast-affirm-0Qo9tk2n-py3.7/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/Users/francisco.arceo/Library/Caches/pypoetry/virtualenvs/feast-affirm-0Qo9tk2n-py3.7/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/francisco.arceo/Library/Caches/pypoetry/virtualenvs/feast-affirm-0Qo9tk2n-py3.7/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/Users/francisco.arceo/Library/Caches/pypoetry/virtualenvs/feast-affirm-0Qo9tk2n-py3.7/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/Users/francisco.arceo/Library/Caches/pypoetry/virtualenvs/feast-affirm-0Qo9tk2n-py3.7/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/Users/francisco.arceo/Library/Caches/pypoetry/virtualenvs/feast-affirm-0Qo9tk2n-py3.7/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/Users/francisco.arceo/Library/Caches/pypoetry/virtualenvs/feast-affirm-0Qo9tk2n-py3.7/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS feature_repo_driver_hourly_stats_ek (entity_key)' at line 1")


[mysql-index-patch]% feast apply
/Users/francisco.arceo/github/feast/sdk/python/feast/feature_store.py:566: RuntimeWarning: On demand feature view is an experimental feature. This API is stable, but the functionality does not scale well for offline retrieval
  RuntimeWarning,
No changes to registry
/Users/francisco.arceo/Library/Caches/pypoetry/virtualenvs/feast-affirm-0Qo9tk2n-py3.7/lib/python3.7/site-packages/pymysql/cursors.py:170: Warning: (1050, "Table 'feature_repo_driver_hourly_stats' already exists")
  result = self._query(query)
/Users/francisco.arceo/Library/Caches/pypoetry/virtualenvs/feast-affirm-0Qo9tk2n-py3.7/lib/python3.7/site-packages/pymysql/cursors.py:170: Warning: (1050, "Table 'feature_repo_driver_hourly_stats_stream' already exists")
  result = self._query(query)
Deploying infrastructure for driver_hourly_stats
Deploying infrastructure for driver_hourly_stats_stream
```

**Pull request merged**
