### PR TITLE
config: making this bad boy build for python3.7

### PR DESCRIPTION
**Pull request by franciscojavierarceo**
**What this PR does / why we need it**:
Downgrades NumPy and Pandas to maintain. support for Python3.7.

**Which issue(s) this PR fixes**:

Fixes #

### CODE REVIEW

**Comment by Rostifar** [comment]
Exciting! Is it enough to just make this change or is there more to come?

**Comment by hao-affirm** [comment]
> **What this PR does / why we need it**: Downgrades NumPy and Pandas to maintain. support for Python3.7.
> 
> **Which issue(s) this PR fixes**:
> 
> Fixes #

I have this branch ready: https://github.com/Affirm/feast/tree/0.23-affirm-0.1
for master we have to keep it clean to be able to sync with feast main repo

**Comment by franciscojavierarceo** [comment]
> > **What this PR does / why we need it**: Downgrades NumPy and Pandas to maintain. support for Python3.7.
> > **Which issue(s) this PR fixes**:
> > Fixes #
> 
> I have this branch ready: https://github.com/Affirm/feast/tree/0.23-affirm-0.1 for master we have to keep it clean to be able to sync with feast main repo

makes sense, i'll change the default branch

**Comment by hao-affirm** [comment]
> > **What this PR does / why we need it**: Downgrades NumPy and Pandas to maintain. support for Python3.7.
> > **Which issue(s) this PR fixes**:
> > Fixes #
> 
> I have this branch ready: https://github.com/Affirm/feast/tree/0.23-affirm-0.1 for master we have to keep it clean to be able to sync with feast main repo

```
    "google-api-core",
    "googleapis-common-protos",
    "grpcio-reflection",
    "numpy<1.22,<2",
    "pandas>=1,<2",
    "protobuf",
    "proto-plus",
    "PyYAML",
    "uvicorn[standard]",
    "tensorflow-metadata",
    "dask",
```
those are all conflicting dependencies :(

**Comment by franciscojavierarceo** [comment]
@hao-affirm which changes should i incorporate into this then? Just the setup.py?

**Comment by hao-affirm** [comment]
> @hao-affirm which changes should i incorporate into this then? Just the setup.py?

I'll get that work soon. the dependency is comlex so i'll take care of it as i already figured out the correct versions. doing some testing in ofs environment now

**Comment by franciscojavierarceo** [comment]
@hao-affirm should I close this PR then? are you going to open a different one? or will you take this one over?

**Comment by franciscojavierarceo** [comment]
closing in favor of: https://github.com/Affirm/feast/pull/2

**Pull request closed without merging**
